name: CI

on:
  push:
    branches:
      - main

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Update Playwright config for headless = false
        run: |
          echo "module.exports = { use: { headless: false } }" > playwright.config.js
      - name: Run tests
        run: npx playwright test
